spring:
  application:
    name: minto-backend

  data:
    mongodb:
      uri: mongodb+srv://jihak:MKhhL7Wnu4lVxd3e@cluster0.kv5caik.mongodb.net/mintoDB?retryWrites=true&w=majority

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK